name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/ec2_key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd ~/nodejs-cicd-demo

          git pull origin main

          npm install

          pm2 restart express-app || pm2 start index.js --name express-app

          pm2 save

          EOF
